# Model

In [10]:
# Initialize Dataset

from pathlib import Path
import pandas as pd

train_path = Path.cwd().parent / "dataset" / "university_query_train.csv"
test_path = Path.cwd().parent / "dataset" / "university_query_test.csv"

train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)

In [11]:
train_df.head()

,Query_ID,Student_Query,Department,Days_To_Deadline,Priority_Label
0,1783,How to join student clubs?,Examination Cell,31,Low
1,3918,My admit card has incorrect details.,Examination Cell,48,High
2,222,How to reset my university portal password?,Finance Office,5,Medium
3,2136,My exam form is not submitted and tomorrow is ...,Academic Office,18,High
4,5225,I cannot download my hall ticket for tomorrow'...,Administration,43,High

In [12]:
test_df.head()

,Query_ID,Student_Query,Department,Days_To_Deadline,Priority_Label
0,2713,LMS is not allowing assignment upload.,IT Support,2,Medium
1,993,How to reset my university portal password?,IT Support,12,Medium
2,2191,I cannot download my hall ticket for tomorrow'...,Academic Office,57,High
3,4671,Fee payment deadline is today but portal is no...,Finance Office,2,High
4,3763,I cannot download my hall ticket for tomorrow'...,IT Support,2,High

In [13]:
print(train_df.shape)
print(test_df.shape)

(5000, 5)
(1000, 5)